### ISSUE TITLE
.editorconfig file makes the solution unbuildable in Visual Studio 

### ISSUE THREAD

**Issue by Bit-Shifts** [epam/fix-antenna-net-core#81]
1) Clone Repo
2) Main Branch
3) Open Solution in Visual Studio 2022
4) Build

Error : 

`private readonly SemaphoreSlim _msgBufferSemaphore = new SemaphoreSlim(1);`

CA2213 : Disposable fields should be disposed  - Error

The .editorconfig stops solution from building due to this.

**Comment by OlehVasylievEPAM** [comment]
Hello [Bit-Shifts](https://github.com/Bit-Shifts)

Thanks for reporting the issue. We have updated the solution to make it buildable. The PR - https://github.com/epam/fix-antenna-net-core/pull/82

We missed the issue, because of the old MSBuild version. We will provide a proper fix in the next release.
